### GetToken
@username = 'teste@teste.com'
@password = '415782'
@clientId = 'newspace-client'
@grantType = 'password'

POST http://localhost:3000/api/auth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic ZGF2aWQuamVyZW1pYXNAcGxhdGZvcm1idWlsZGVyLmlvOjQxNTc4Mg==

clientId={{clientId}}&grantType={{grantType}}



### Created
POST http://localhost:3000/api/user
Content-Type: application/json

{
    "name": "David Jeremias",
    "username": "david.jeremias@platformbuilder.io",
    "password": "415782",
    "roles": ["CORRESPONDENTE_BANCARIO"]
}


### FindOne
GET http://localhost:3000/api/user/1


### FindOneByUsername
GET http://localhost:3000/api/user/username/david.jeremias@platformbuilder.io


### FindAll
GET http://localhost:3000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhdmlkLmplcmVtaWFzQHBsYXRmb3JtYnVpbGRlci5pbyIsInN1YiI6MSwiaWF0IjoxNjQxNDk1MDAzLCJleHAiOjE2NDE0OTUzMDN9.4WC5-5uuwaqHMRI4b3p1PFCTNntdnLRFT7BIrOaldLY

### FindAllPageable
GET http://localhost:3000/api/user/pageable?offset=0&limit=10



PATCH http://localhost:3000/api/user/1
Content-Type: application/json

{
    "username": "david.jeremias.souza@platformbuilder.io"
}


### Delete
DELETE http://localhost:3000/api/user/1


### CLIENT

### Created
POST http://localhost:3000/api/client
Content-Type: application/json

{
    "name": "David Jeremias"
}


### FindAll
GET http://localhost:3000/api/client


### CACHE

### Created
POST http://localhost:3000/api/redis
Content-Type: application/json

{
    "key": "nome",
    "value": "David Jeremias"
}


### Find
GET http://localhost:3000/api/redis/nome
